USE WAREHOUSE COMPUTE_WH;

USE ROLE ACCOUNTADMIN;

--create 'transform' role
DROP ROLE IF EXISTS TRANSFORM;
CREATE ROLE TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- grant access to the wh
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- create the "dbt" user and assign to role
DROP USER IF EXISTS dbt;
CREATE USER IF NOT EXISTS dbt
    LOGIN_NAME = 'dbt'
    TYPE = SERVICE
    RSA_PUBLIC_KEY = "add_your_own_rsa_public_key_here"
    DEFAULT_ROLE = TRANSFORM
    DEFAULT_WAREHOUSE = 'COMPUTE_WH'
    DEFAULT_NAMESPACE = 'AIRBNB.RAW'
    COMMENT = 'DBT user for data transformation';

GRANT ROLE TRANSFORM TO USER dbt;

-- Set up permissions to role `transform.`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;