airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: XOCJZHF-CP55872
      user: dbt
      role: TRANSFORM

      private_key_path: "/Users/juanfelipehernandezm/snow_dbt_key.p8"
      private_key_passphrase: dbt

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: true
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None

      